import LenisScrollProvider from "@/providers/lenis-scroll";
import { NextThemeProvider } from "@/providers/next-theme";
import ReactQueryProvider from "@/providers/react-query";
import type { Metadata } from "next";
import { DM_Sans, Poppins, Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "FYP Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body
        className={`${poppins.className} ${dmSans.variable} ${inter.variable} bg-body-gradient antialiased`}
      >
        <Toaster position="bottom-right" />
        <NextThemeProvider
          attribute={"class"}
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <LenisScrollProvider>
              <Header />
              {children}
            </LenisScrollProvider>
          </ReactQueryProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
